import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
import axios from "axios";

export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results res={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  var myHeaders = new Headers();
  myHeaders.append("Accept", "application/json");

  var requestOptions = {
    method: "GET",
    headers: myHeaders,
  };

  var request = null;

  await axios
    .get(
      `https://api.themoviedb.org/3${
        requests[genre]?.url || requests.fetchTrending.url
      }`

      // "https://api.themoviedb.org/3/movie/550?api_key=d6e8c0a145b0ca9d794148c003b76c2a"
    )
    .then((res) => {
      request = res.data;
      console.log(res.data);
    });

  return {
    props: {
      results: request.results,
    },
  };
}
